// Package web provides a minimal HTTP server that renders app.ViewState as
// HTML, accepting semantic Actions via POST /action and exposing the current
// state as JSON via GET /state. It is the web renderer counterpart to
// internal/tui.
//
// Security model (mandatory — this endpoint serves live AWS state):
//   - Binds 127.0.0.1 only; --web-addr configurable but never defaults to 0.0.0.0.
//   - Host-header validation on every request: rejects any Host whose host part
//     is not a loopback address (127.x.x.x, ::1, localhost). Defeats DNS-rebinding
//     attacks where a hostile page resolves its hostname to 127.0.0.1 and then
//     issues requests against this listener.
//   - Origin-header validation when present: rejects cross-origin requests whose
//     Origin host is not loopback. Same-origin GETs and EventSource connections
//     may omit Origin; the check is skipped when the header is absent.
//   - Random per-run token required on every /action, /state, /events, /body request.
//   - No CORS headers. Cache-Control: no-store on all responses.
//   - Per-session *app.Controller keyed by session cookie.
//   - CSRF protection on POST /action via custom header X-A9S-Token.
//   - Constant-time token comparison via crypto/subtle.
//   - ActionReveal blocked unless --web-allow-reveal is set.
package web

import (
	"context"
	"net"
	"net/http"
	"sync"
	"time"

	"github.com/k2m30/a9s/v3/internal/app"
	"github.com/k2m30/a9s/v3/internal/config"
)

// sessionEntry holds the per-browser-session controller and its action mutex.
// The controller itself is concurrency-safe (RWMutex), but we serialize
// actions per session so two in-flight POSTs can't interleave.
type sessionEntry struct {
	ctrl *app.Controller
	mu   sync.Mutex
}

// Server is the web renderer. One instance per process; one Controller per
// browser session (keyed by session cookie).
type Server struct {
	// opts supplied at construction time.
	profile      string
	region       string
	command      string
	demoMode     bool
	noCache      bool
	allowReveal  bool
	addr         string
	viewCfg      *config.ViewsConfig

	// token is the random per-run auth token embedded into every served page.
	token string

	// sessions is the per-browser-session store.
	sessions   map[string]*sessionEntry
	sessionsMu sync.Mutex
}

// NewServer constructs a Server. token must be a cryptographically-random
// value (generated by the caller via generateToken). addr is the listen
// address (e.g. "127.0.0.1:7682").
func NewServer(profile, region, command, addr, token string, demoMode, noCache, allowReveal bool, viewCfg *config.ViewsConfig) *Server {
	return &Server{
		profile:     profile,
		region:      region,
		command:     command,
		demoMode:    demoMode,
		noCache:     noCache,
		allowReveal: allowReveal,
		addr:        addr,
		token:       token,
		viewCfg:     viewCfg,
		sessions:    make(map[string]*sessionEntry),
	}
}

// ListenAndServe binds the server, updates s.addr with the resolved address
// (important when the port is 0), closes readyCh to signal the caller that
// the address is available, then blocks until ctx is cancelled.
// On ctx cancellation a graceful 5-second shutdown is performed.
func (s *Server) ListenAndServe(ctx context.Context, readyCh chan<- struct{}) error {
	mux := http.NewServeMux()
	s.registerRoutes(mux)

	srv := &http.Server{
		Addr:    s.addr,
		Handler: mux,
		// SSE connections are long-lived; WriteTimeout is intentionally zero.
		ReadHeaderTimeout: 10 * time.Second,
	}

	lc := &net.ListenConfig{}
	ln, err := lc.Listen(ctx, "tcp", s.addr)
	if err != nil {
		return err
	}
	s.addr = ln.Addr().String()

	// Signal the caller that the address is now known.
	if readyCh != nil {
		close(readyCh)
	}

	errCh := make(chan error, 1)
	go func() {
		if serveErr := srv.Serve(ln); serveErr != nil && serveErr != http.ErrServerClosed {
			errCh <- serveErr
		}
		close(errCh)
	}()

	select {
	case <-ctx.Done():
		shutCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = srv.Shutdown(shutCtx)
		return <-errCh
	case serveErr := <-errCh:
		return serveErr
	}
}

// Addr returns the resolved listen address after ListenAndServe has started.
// Useful when addr was "127.0.0.1:0" (OS-assigned port).
func (s *Server) Addr() string { return s.addr }

// Token returns the per-run auth token.
func (s *Server) Token() string { return s.token }

// dnsRebindGuard is middleware that rejects any request whose Host header is
// not a loopback address, and any request that carries a non-loopback Origin
// header. This defeats DNS-rebinding attacks: a hostile page whose hostname
// resolves to 127.0.0.1 is blocked because its Host value is not loopback.
// Static assets are also guarded so an attacker cannot use them as an oracle.
func (s *Server) dnsRebindGuard(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !hostOK(r) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// registerRoutes wires all HTTP handlers to mux, wrapped in DNS-rebind guard.
func (s *Server) registerRoutes(mux *http.ServeMux) {
	mux.Handle("GET /", s.dnsRebindGuard(http.HandlerFunc(s.handleIndex)))
	mux.Handle("POST /action", s.dnsRebindGuard(http.HandlerFunc(s.handleAction)))
	mux.Handle("GET /body", s.dnsRebindGuard(http.HandlerFunc(s.handleBody)))
	mux.Handle("GET /state", s.dnsRebindGuard(http.HandlerFunc(s.handleState)))
	mux.Handle("GET /events", s.dnsRebindGuard(http.HandlerFunc(s.handleEvents)))
	mux.Handle("GET /static/", s.dnsRebindGuard(http.StripPrefix("/static/", http.FileServer(http.FS(staticContent)))))
}

// getOrCreateSession returns (or lazily creates) the session for the given
// session-cookie value. A new Controller is bootstrapped for each new session.
func (s *Server) getOrCreateSession(sessionID string) *sessionEntry {
	s.sessionsMu.Lock()
	if entry, ok := s.sessions[sessionID]; ok {
		s.sessionsMu.Unlock()
		return entry
	}
	ctrl := newSession(s.profile, s.region, s.command, s.demoMode, s.noCache, s.viewCfg)
	entry := &sessionEntry{ctrl: ctrl}
	s.sessions[sessionID] = entry
	s.sessionsMu.Unlock()

	// Live sessions connect to AWS in the background so GET / renders the menu
	// immediately; availability is pushed to the browser over SSE once ready.
	// Demo sessions are already fully bootstrapped (pre-supplied clients), so
	// there is nothing to do asynchronously.
	if !s.demoMode {
		go s.bootstrapLiveSession(entry)
	}
	return entry
}

// bootstrapLiveSession performs the AWS connect for a live session and applies
// any startup command, then notifies SSE subscribers so the browser refreshes
// to the populated menu. It runs in its own goroutine and relies on the
// controller's internal locking (not entry.mu), so request handlers are never
// blocked for the connect's duration — the page renders the menu while this
// runs.
func (s *Server) bootstrapLiveSession(entry *sessionEntry) {
	tasks := entry.ctrl.BootstrapLive(s.profile, s.region)
	// Drain the availability fetches with a per-result SSE notify so the menu
	// fills in progressively. Live fetches across all resource types take tens
	// of seconds; a single notify at the end would leave the browser's menu
	// blank that whole time, then populate all at once.
	app.DrainSyncProgress(entry.ctrl, tasks, func() { s.notifySubscribers(entry) })
	if s.command != "" {
		_, ctasks := entry.ctrl.Apply(app.Action{Kind: app.ActionCommand, Arg: s.command})
		app.DrainSync(entry.ctrl, ctasks)
	}
	s.notifySubscribers(entry)
}
