// Package web provides a minimal HTTP server that renders app.ViewState as
// HTML, accepting semantic Actions via POST /action and exposing the current
// state as JSON via GET /state. It is the web renderer counterpart to
// internal/tui.
//
// Security model (mandatory — this endpoint serves live AWS state):
//   - Binds 127.0.0.1 only; --web-addr configurable but never defaults to 0.0.0.0.
//   - Host-header validation on every request: rejects any Host whose host part
//     is not a loopback address (127.x.x.x, ::1, localhost). Defeats DNS-rebinding
//     attacks where a hostile page resolves its hostname to 127.0.0.1 and then
//     issues requests against this listener.
//   - Origin-header validation when present: rejects cross-origin requests whose
//     Origin host is not loopback. Same-origin GETs and EventSource connections
//     may omit Origin; the check is skipped when the header is absent.
//   - Random per-run token required on every GET / (page embeds the real token),
//     /action, /state, /events, /body request.
//   - No CORS headers. Cache-Control: no-store on all responses.
//   - Per-session *app.Controller keyed by session cookie.
//   - CSRF protection on POST /action via custom header X-A9S-Token.
//   - Constant-time token comparison via crypto/subtle.
//   - ActionReveal blocked unless --web-allow-reveal is set.
package web

import (
	"context"
	"net"
	"net/http"
	"sync"
	"time"

	"github.com/k2m30/a9s/v3/internal/app"
	"github.com/k2m30/a9s/v3/internal/config"
	"github.com/k2m30/a9s/v3/internal/runtime"
)

// sessionEntry holds the per-browser-session controller and its action mutex.
// The controller itself is concurrency-safe (RWMutex), but we serialize
// actions per session so two in-flight POSTs can't interleave.
type sessionEntry struct {
	ctrl *app.Controller
	mu   sync.Mutex

	// inFlight dedups background task drains keyed by runtime.TaskKey (kind +
	// scope): re-opening the same detail mid-flight must not stack a second
	// concurrent related-check/enrich fan-out for the same key. Entries are
	// deleted on completion. Guarded by inFlightMu, independent of mu (the
	// background drain never holds entry.mu — see drainBackgroundTasks).
	inFlight   map[runtime.TaskKey]struct{}
	inFlightMu sync.Mutex
}

// Server is the web renderer. One instance per process; one Controller per
// browser session (keyed by session cookie).
type Server struct {
	// opts supplied at construction time.
	profile     string
	region      string
	command     string
	demoMode    bool
	noCache     bool
	allowReveal bool
	addr        string
	viewCfg     *config.ViewsConfig

	// token is the random per-run auth token embedded into every served page.
	token string

	// sessions is the per-browser-session store.
	sessions   map[string]*sessionEntry
	sessionsMu sync.Mutex
}

// NewServer constructs a Server. token must be a cryptographically-random
// value (generated by the caller via generateToken). addr is the listen
// address (e.g. "127.0.0.1:7682").
func NewServer(profile, region, command, addr, token string, demoMode, noCache, allowReveal bool, viewCfg *config.ViewsConfig) *Server {
	return &Server{
		profile:     profile,
		region:      region,
		command:     command,
		demoMode:    demoMode,
		noCache:     noCache,
		allowReveal: allowReveal,
		addr:        addr,
		token:       token,
		viewCfg:     viewCfg,
		sessions:    make(map[string]*sessionEntry),
	}
}

// ListenAndServe binds the server, updates s.addr with the resolved address
// (important when the port is 0), closes readyCh to signal the caller that
// the address is available, then blocks until ctx is cancelled.
// On ctx cancellation a graceful 5-second shutdown is performed.
func (s *Server) ListenAndServe(ctx context.Context, readyCh chan<- struct{}) error {
	mux := http.NewServeMux()
	s.registerRoutes(mux)

	srv := &http.Server{
		Addr:    s.addr,
		Handler: mux,
		// SSE connections are long-lived; WriteTimeout is intentionally zero.
		ReadHeaderTimeout: 10 * time.Second,
	}

	lc := &net.ListenConfig{}
	ln, err := lc.Listen(ctx, "tcp", s.addr)
	if err != nil {
		return err
	}
	s.addr = ln.Addr().String()

	// Signal the caller that the address is now known.
	if readyCh != nil {
		close(readyCh)
	}

	errCh := make(chan error, 1)
	go func() {
		if serveErr := srv.Serve(ln); serveErr != nil && serveErr != http.ErrServerClosed {
			errCh <- serveErr
		}
		close(errCh)
	}()

	select {
	case <-ctx.Done():
		shutCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = srv.Shutdown(shutCtx)
		return <-errCh
	case serveErr := <-errCh:
		return serveErr
	}
}

// Addr returns the resolved listen address after ListenAndServe has started.
// Useful when addr was "127.0.0.1:0" (OS-assigned port).
func (s *Server) Addr() string { return s.addr }

// Token returns the per-run auth token.
func (s *Server) Token() string { return s.token }

// dnsRebindGuard is middleware that rejects any request whose Host header is
// not a loopback address, and any request that carries a non-loopback Origin
// header. This defeats DNS-rebinding attacks: a hostile page whose hostname
// resolves to 127.0.0.1 is blocked because its Host value is not loopback.
// Static assets are also guarded so an attacker cannot use them as an oracle.
func (s *Server) dnsRebindGuard(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !hostOK(r) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// registerRoutes wires all HTTP handlers to mux, wrapped in DNS-rebind guard.
func (s *Server) registerRoutes(mux *http.ServeMux) {
	mux.Handle("GET /", s.dnsRebindGuard(http.HandlerFunc(s.handleIndex)))
	mux.Handle("POST /action", s.dnsRebindGuard(http.HandlerFunc(s.handleAction)))
	mux.Handle("GET /body", s.dnsRebindGuard(http.HandlerFunc(s.handleBody)))
	mux.Handle("GET /state", s.dnsRebindGuard(http.HandlerFunc(s.handleState)))
	mux.Handle("GET /events", s.dnsRebindGuard(http.HandlerFunc(s.handleEvents)))
	mux.Handle("GET /static/", s.dnsRebindGuard(http.StripPrefix("/static/", http.FileServer(http.FS(staticContent)))))
}

// getOrCreateSession returns (or lazily creates) the session for the given
// session-cookie value. A new Controller is bootstrapped for each new session.
func (s *Server) getOrCreateSession(sessionID string) *sessionEntry {
	s.sessionsMu.Lock()
	if entry, ok := s.sessions[sessionID]; ok {
		s.sessionsMu.Unlock()
		return entry
	}
	ctrl := newSession(s.profile, s.region, s.command, s.demoMode, s.noCache, s.viewCfg)
	entry := &sessionEntry{ctrl: ctrl, inFlight: make(map[runtime.TaskKey]struct{})}
	s.sessions[sessionID] = entry
	s.sessionsMu.Unlock()

	// Live sessions connect to AWS in the background so GET / renders the menu
	// immediately; availability is pushed to the browser over SSE once ready.
	// Demo sessions are already fully bootstrapped (pre-supplied clients), so
	// there is nothing to do asynchronously.
	if !s.demoMode {
		go s.bootstrapLiveSession(entry)
	}
	return entry
}

// bootstrapLiveSession performs the AWS connect for a live session and drains
// the full availability sweep in the background — mirroring the TUI lane's
// ClientsReady-time dispatch. Any startup command (-c) is no longer applied
// here: newSession arms it via Core.SetCommand (the same runtime.Core.Session
// .Command field tui.WithCommand sets), so BootstrapLive's HandleClientsReady
// call below arms session.CommandArmed/PendingCommand itself, and the
// DrainSyncProgress call's per-task interception of TaskKindEmitNavigate
// (see drainsync.go) applies the deferred navigation the moment
// handleAvailabilityCacheLoaded emits it — the same one lane the TUI's -c
// flag drives (DEF-14/D11), instead of a second server-side apply racing or
// duplicating it.
//
// It runs in its own goroutine and relies on the controller's internal
// locking (not entry.mu), so request handlers are never blocked for the
// connect's duration — the page renders the menu while this runs.
func (s *Server) bootstrapLiveSession(entry *sessionEntry) {
	tasks := entry.ctrl.BootstrapLive(s.profile, s.region)

	// Drain the availability fetches (and, when armed, the deferred -c
	// navigation task nested among them) with a per-result SSE notify so the
	// menu — and the navigated screen, the instant it lands — fills in
	// progressively. Live fetches across all resource types take tens of
	// seconds; a single notify at the end would leave the browser blank that
	// whole time, then populate all at once.
	app.DrainSyncProgress(entry.ctrl, tasks, func() { s.notifySubscribers(entry) })
	s.notifySubscribers(entry)
}

// backgroundDrainTimeout bounds a single background-task drain (related-check
// fan-out, detail enrichment, save-cache). 60s comfortably covers a live
// (non-demo) related-check fan-out across many resource types without risking
// an unbounded goroutine on a slow/hung AWS call.
const backgroundDrainTimeout = 60 * time.Second

// drainBackgroundTasks runs pending (already partitioned as background by
// handleAction via app.DrainSyncPartition) to completion in its own
// goroutine, notifying SSE subscribers as each result lands and once more
// when the drain finishes. It does NOT hold entry.mu while draining — mirrors
// bootstrapLiveSession's locking model, so in-flight POST/GET handlers for
// the same session are never blocked on a slow related-check/enrich fan-out.
//
// In-flight dedup: pending tasks whose Key is already draining (tracked in
// entry.inFlight) are skipped so re-opening the same detail mid-flight does
// not stack a second concurrent fan-out for the same key. Each drained key is
// removed from entry.inFlight on completion (success or timeout).
func (s *Server) drainBackgroundTasks(entry *sessionEntry, pending []runtime.TaskRequest) {
	if len(pending) == 0 {
		return
	}

	entry.inFlightMu.Lock()
	deduped := pending[:0:0]
	for _, t := range pending {
		if _, running := entry.inFlight[t.Key]; running {
			continue
		}
		entry.inFlight[t.Key] = struct{}{}
		deduped = append(deduped, t)
	}
	entry.inFlightMu.Unlock()

	if len(deduped) == 0 {
		return
	}

	go func() {
		defer func() {
			entry.inFlightMu.Lock()
			for _, t := range deduped {
				delete(entry.inFlight, t.Key)
			}
			entry.inFlightMu.Unlock()
		}()

		ctx, cancel := context.WithTimeout(context.Background(), backgroundDrainTimeout)
		defer cancel()

		app.DrainSyncContextProgress(ctx, entry.ctrl, deduped, func() { s.notifySubscribers(entry) })
		s.notifySubscribers(entry)
	}()
}
