version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosec
    - gocritic
    - bodyclose
    - prealloc
    - noctx

  exclusions:
    paths:
      - tests/testdata

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gosec:
      excludes:
        - G104
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
