version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosec
    - gocritic
    - bodyclose
    - noctx

  exclusions:
    paths:
      - tests/testdata
    rules:
      - linters: [gosec]
        path: '_test\.go$'
      - linters: [errcheck]
        path: '_test\.go$'

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gosec:
      excludes:
        - G104
        - G304
    gocritic:
      enabled-tags:
        - diagnostic
      disabled-checks:
        - singleCaseSwitch
