version: 2

before:
  hooks:
    - go mod download

builds:
  - id: a9s
    main: ./cmd/a9s
    binary: a9s
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ .Date }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

brews:
  - repository:
      owner: k2m30
      name: homebrew-a9s
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/k2m30/a9s
    description: Terminal UI AWS Resource Manager
    license: GPL-3.0-or-later
    test: |
      system "#{bin}/a9s", "--version"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  prerelease: auto
