package resource

func networkingResourceTypes() []ResourceTypeDef {
	return []ResourceTypeDef{
		{
			Name:      "Load Balancers",
			ShortName: "elb",
			Aliases:   []string{"elb", "alb", "nlb", "loadbalancers", "load-balancers"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "name", Title: "Name", Width: 32, Sortable: true},
				{Key: "dns_name", Title: "DNS Name", Width: 48, Sortable: false},
				{Key: "type", Title: "Type", Width: 12, Sortable: true},
				{Key: "scheme", Title: "Scheme", Width: 14, Sortable: true},
				{Key: "state", Title: "State", Width: 12, Sortable: true},
				{Key: "vpc_id", Title: "VPC ID", Width: 24, Sortable: true},
			},
		},
		{
			Name:      "Target Groups",
			ShortName: "tg",
			Aliases:   []string{"tg", "targetgroups", "target-groups"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "target_group_name", Title: "Target Group", Width: 32, Sortable: true},
				{Key: "port", Title: "Port", Width: 8, Sortable: true},
				{Key: "protocol", Title: "Protocol", Width: 10, Sortable: true},
				{Key: "vpc_id", Title: "VPC ID", Width: 24, Sortable: true},
				{Key: "target_type", Title: "Target Type", Width: 12, Sortable: true},
				{Key: "health_check_path", Title: "Health Check", Width: 24, Sortable: false},
			},
			Children: []ChildViewDef{{
				ChildType:      "tg_health",
				Key:            "enter",
				ContextKeys:    map[string]string{"target_group_arn": "target_group_arn"},
				DisplayNameKey: "Name",
			}},
		},
		{
			Name:      "Security Groups",
			ShortName: "sg",
			Aliases:   []string{"sg", "securitygroups", "security-groups"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "group_id", Title: "Group ID", Width: 24, Sortable: true},
				{Key: "group_name", Title: "Group Name", Width: 28, Sortable: true},
				{Key: "vpc_id", Title: "VPC ID", Width: 24, Sortable: true},
				{Key: "description", Title: "Description", Width: 36, Sortable: false},
			},
		},
		{
			Name:      "VPCs",
			ShortName: "vpc",
			Aliases:   []string{"vpc", "vpcs"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "vpc_id", Title: "VPC ID", Width: 24, Sortable: true},
				{Key: "name", Title: "Name", Width: 24, Sortable: true},
				{Key: "cidr_block", Title: "CIDR Block", Width: 18, Sortable: true},
				{Key: "state", Title: "State", Width: 12, Sortable: true},
				{Key: "is_default", Title: "Default", Width: 9, Sortable: true},
			},
		},
		{
			Name:      "Subnets",
			ShortName: "subnet",
			Aliases:   []string{"subnet", "subnets"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "subnet_id", Title: "Subnet ID", Width: 26, Sortable: true},
				{Key: "name", Title: "Name", Width: 28, Sortable: true},
				{Key: "vpc_id", Title: "VPC ID", Width: 24, Sortable: true},
				{Key: "cidr_block", Title: "CIDR Block", Width: 18, Sortable: true},
				{Key: "availability_zone", Title: "AZ", Width: 14, Sortable: true},
				{Key: "state", Title: "State", Width: 12, Sortable: true},
				{Key: "available_ips", Title: "Available IPs", Width: 14, Sortable: true},
			},
		},
		{
			Name:      "Route Tables",
			ShortName: "rtb",
			Aliases:   []string{"rtb", "routetables", "route-tables"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "route_table_id", Title: "Route Table ID", Width: 26, Sortable: true},
				{Key: "name", Title: "Name", Width: 28, Sortable: true},
				{Key: "vpc_id", Title: "VPC ID", Width: 24, Sortable: true},
				{Key: "routes_count", Title: "Routes", Width: 8, Sortable: true},
				{Key: "associations_count", Title: "Assoc.", Width: 8, Sortable: true},
			},
		},
		{
			Name:      "NAT Gateways",
			ShortName: "nat",
			Aliases:   []string{"nat", "natgateways", "nat-gateways"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "nat_gateway_id", Title: "NAT Gateway ID", Width: 26, Sortable: true},
				{Key: "name", Title: "Name", Width: 24, Sortable: true},
				{Key: "vpc_id", Title: "VPC ID", Width: 24, Sortable: true},
				{Key: "subnet_id", Title: "Subnet ID", Width: 26, Sortable: true},
				{Key: "state", Title: "State", Width: 12, Sortable: true},
				{Key: "public_ip", Title: "Public IP", Width: 16, Sortable: false},
			},
		},
		{
			Name:      "Internet Gateways",
			ShortName: "igw",
			Aliases:   []string{"igw", "internetgateways", "internet-gateways"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "igw_id", Title: "IGW ID", Width: 26, Sortable: true},
				{Key: "name", Title: "Name", Width: 28, Sortable: true},
				{Key: "vpc_id", Title: "VPC ID", Width: 24, Sortable: true},
				{Key: "state", Title: "State", Width: 12, Sortable: true},
			},
		},
		{
			Name:      "Elastic IPs",
			ShortName: "eip",
			Aliases:   []string{"eip", "elastic-ips", "elasticips"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "allocation_id", Title: "Allocation ID", Width: 26, Sortable: true},
				{Key: "name", Title: "Name", Width: 24, Sortable: true},
				{Key: "public_ip", Title: "Public IP", Width: 16, Sortable: true},
				{Key: "association_id", Title: "Association", Width: 26, Sortable: true},
				{Key: "instance_id", Title: "Instance", Width: 20, Sortable: true},
				{Key: "domain", Title: "Domain", Width: 8, Sortable: true},
			},
		},
		{
			Name:      "VPC Endpoints",
			ShortName: "vpce",
			Aliases:   []string{"vpce", "vpc-endpoints", "vpcendpoints"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "vpce_id", Title: "Endpoint ID", Width: 26, Sortable: true},
				{Key: "service_name", Title: "Service Name", Width: 40, Sortable: true},
				{Key: "type", Title: "Type", Width: 12, Sortable: true},
				{Key: "state", Title: "State", Width: 12, Sortable: true},
				{Key: "vpc_id", Title: "VPC ID", Width: 24, Sortable: true},
			},
		},
		{
			Name:      "Transit Gateways",
			ShortName: "tgw",
			Aliases:   []string{"tgw", "transit-gateways", "transitgateways"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "tgw_id", Title: "TGW ID", Width: 26, Sortable: true},
				{Key: "name", Title: "Name", Width: 28, Sortable: true},
				{Key: "state", Title: "State", Width: 12, Sortable: true},
				{Key: "owner_id", Title: "Owner", Width: 14, Sortable: true},
				{Key: "description", Title: "Description", Width: 30, Sortable: false},
			},
		},
		{
			Name:      "Network Interfaces",
			ShortName: "eni",
			Aliases:   []string{"eni", "network-interfaces", "nis"},
			Category:  "NETWORKING",
			Columns: []Column{
				{Key: "eni_id", Title: "ENI ID", Width: 26, Sortable: true},
				{Key: "name", Title: "Name", Width: 24, Sortable: true},
				{Key: "status", Title: "Status", Width: 12, Sortable: true},
				{Key: "type", Title: "Type", Width: 14, Sortable: true},
				{Key: "vpc_id", Title: "VPC ID", Width: 24, Sortable: true},
				{Key: "private_ip", Title: "Private IP", Width: 16, Sortable: false},
			},
		},
	}
}
