#!/bin/sh
# generate-homebrew-formula.sh — render Formula/a9s.rb for k2m30/homebrew-a9s.
#
#   scripts/generate-homebrew-formula.sh <version> <checksums.txt> > a9s.rb
#
# Replaces GoReleaser's deprecated `brews:` generator (issue #455): the cask
# migration broke macOS UX (quarantine on unsigned binaries), so releases keep
# publishing a FORMULA, rendered from the checksums GoReleaser already emits.
# The template mirrors the last known-good GoReleaser-generated formula
# (v3.45.0) byte-for-byte in structure, so `brew install k2m30/a9s/a9s`
# behavior is unchanged.
#
# Fails hard if any of the four platform archives is missing from the
# checksums file — a partial formula must never reach the tap.
set -eu

VERSION="${1:?usage: generate-homebrew-formula.sh <version> <checksums.txt>}"
CHECKSUMS="${2:?usage: generate-homebrew-formula.sh <version> <checksums.txt>}"

sha_for() {
	archive="a9s_${VERSION}_$1.tar.gz"
	sha=$(awk -v f="$archive" '$2 == f { print $1 }' "$CHECKSUMS")
	if [ -z "$sha" ]; then
		echo "generate-homebrew-formula: no sha256 for ${archive} in ${CHECKSUMS}" >&2
		exit 1
	fi
	printf '%s' "$sha"
}

DARWIN_AMD64=$(sha_for darwin_amd64)
DARWIN_ARM64=$(sha_for darwin_arm64)
LINUX_AMD64=$(sha_for linux_amd64)
LINUX_ARM64=$(sha_for linux_arm64)

cat <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by scripts/generate-homebrew-formula.sh (k2m30/a9s). DO NOT EDIT.
class A9s < Formula
  desc "Terminal UI AWS Resource Manager"
  homepage "https://github.com/k2m30/a9s"
  version "${VERSION}"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k2m30/a9s/releases/download/v${VERSION}/a9s_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"

      define_method(:install) do
        bin.install "a9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k2m30/a9s/releases/download/v${VERSION}/a9s_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"

      define_method(:install) do
        bin.install "a9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/k2m30/a9s/releases/download/v${VERSION}/a9s_${VERSION}_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
      define_method(:install) do
        bin.install "a9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k2m30/a9s/releases/download/v${VERSION}/a9s_${VERSION}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
      define_method(:install) do
        bin.install "a9s"
      end
    end
  end

  test do
    system "#{bin}/a9s", "--version"
  end
end
EOF
