// SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-Commercial

package iampolicy

// privEscCombos is Prowler's privilege_escalation_policies_combination
// (prowler/providers/aws/services/iam/lib/privilege_escalation.py), names
// verbatim; a combo matches when every listed action is allowed.
var privEscCombos = map[string][]string{
	"OverPermissiveIAM":                                                  {"iam:*"},
	"IAMPut":                                                             {"iam:Put*"},
	"CreatePolicyVersion":                                                {"iam:CreatePolicyVersion"},
	"SetDefaultPolicyVersion":                                            {"iam:SetDefaultPolicyVersion"},
	"iam:CreateAccessKey":                                                {"iam:CreateAccessKey"},
	"iam:CreateLoginProfile":                                             {"iam:CreateLoginProfile"},
	"iam:UpdateLoginProfile":                                             {"iam:UpdateLoginProfile"},
	"iam:AttachUserPolicy":                                               {"iam:AttachUserPolicy"},
	"iam:AttachGroupPolicy":                                              {"iam:AttachGroupPolicy"},
	"iam:AttachRolePolicy":                                               {"iam:AttachRolePolicy"},
	"iam:PutGroupPolicy":                                                 {"iam:PutGroupPolicy"},
	"iam:PutRolePolicy":                                                  {"iam:PutRolePolicy"},
	"iam:PutUserPolicy":                                                  {"iam:PutUserPolicy"},
	"iam:AddUserToGroup":                                                 {"iam:AddUserToGroup"},
	"iam:UpdateAssumeRolePolicy":                                         {"iam:UpdateAssumeRolePolicy"},
	"CreateAccessKey+DeleteAccessKey":                                    {"iam:CreateAccessKey", "iam:DeleteAccessKey"},
	"AttachUserPolicy+CreateAccessKey":                                   {"iam:AttachUserPolicy", "iam:CreateAccessKey"},
	"PutUserPolicy+CreateAccessKey":                                      {"iam:CreateAccessKey", "iam:PutUserPolicy"},
	"AttachRolePolicy+UpdateAssumeRolePolicy":                            {"iam:AttachRolePolicy", "iam:UpdateAssumeRolePolicy"},
	"CreatePolicyVersion+UpdateAssumeRolePolicy":                         {"iam:CreatePolicyVersion", "iam:UpdateAssumeRolePolicy"},
	"PutRolePolicy+UpdateAssumeRolePolicy":                               {"iam:PutRolePolicy", "iam:UpdateAssumeRolePolicy"},
	"AssumeRole+AttachRolePolicy":                                        {"iam:AttachRolePolicy", "sts:AssumeRole"},
	"AssumeRole+PutRolePolicy":                                           {"iam:PutRolePolicy", "sts:AssumeRole"},
	"AssumeRole+UpdateAssumeRolePolicy":                                  {"iam:UpdateAssumeRolePolicy", "sts:AssumeRole"},
	"AssumeRole+CreatePolicyVersion":                                     {"iam:CreatePolicyVersion", "sts:AssumeRole"},
	"PassRole+EC2":                                                       {"ec2:RunInstances", "iam:PassRole"},
	"PassRole+EC2SpotInstances":                                          {"ec2:RequestSpotInstances", "iam:PassRole"},
	"EC2ModifyInstanceAttribute":                                         {"ec2:ModifyInstanceAttribute", "ec2:StartInstances", "ec2:StopInstances"},
	"EC2ModifyLaunchTemplate":                                            {"ec2:CreateLaunchTemplateVersion", "ec2:ModifyLaunchTemplate"},
	"EC2InstanceConnect+SendSSHPublicKey":                                {"ec2-instance-connect:SendSSHPublicKey", "ec2:DescribeInstances"},
	"PassRole+CreateLambda+Invoke":                                       {"iam:PassRole", "lambda:CreateFunction", "lambda:InvokeFunction"},
	"PassRole+CreateLambda+ExistingDynamo":                               {"iam:PassRole", "lambda:CreateEventSourceMapping", "lambda:CreateFunction"},
	"PassRole+CreateLambda+NewDynamo":                                    {"dynamodb:CreateTable", "dynamodb:PutItem", "iam:PassRole", "lambda:CreateEventSourceMapping", "lambda:CreateFunction"},
	"PassRole+CreateLambda+AddPermission":                                {"iam:PassRole", "lambda:AddPermission", "lambda:CreateFunction"},
	"lambda:UpdateFunctionCode":                                          {"lambda:UpdateFunctionCode"},
	"lambda:UpdateFunctionConfiguration":                                 {"lambda:UpdateFunctionConfiguration"},
	"UpdateFunctionCode+InvokeFunction":                                  {"lambda:InvokeFunction", "lambda:UpdateFunctionCode"},
	"UpdateFunctionCode+AddPermission":                                   {"lambda:AddPermission", "lambda:UpdateFunctionCode"},
	"PassRole+GlueCreateDevEndpoint":                                     {"glue:CreateDevEndpoint", "iam:PassRole"},
	"GlueUpdateDevEndpoint":                                              {"glue:UpdateDevEndpoint"},
	"PassRole+GlueCreateJob+StartJobRun":                                 {"glue:CreateJob", "glue:StartJobRun", "iam:PassRole"},
	"PassRole+GlueCreateJob+CreateTrigger":                               {"glue:CreateJob", "glue:CreateTrigger", "iam:PassRole"},
	"PassRole+GlueUpdateJob+StartJobRun":                                 {"glue:StartJobRun", "glue:UpdateJob", "iam:PassRole"},
	"PassRole+GlueUpdateJob+CreateTrigger":                               {"glue:CreateTrigger", "glue:UpdateJob", "iam:PassRole"},
	"PassRole+CloudFormationCreateStack":                                 {"cloudformation:CreateStack", "iam:PassRole"},
	"CloudFormationUpdateStack":                                          {"cloudformation:UpdateStack"},
	"PassRole+CloudFormationCreateStackSet":                              {"cloudformation:CreateStackInstances", "cloudformation:CreateStackSet", "iam:PassRole"},
	"PassRole+CloudFormationUpdateStackSet":                              {"cloudformation:UpdateStackSet", "iam:PassRole"},
	"CloudFormationChangeSet":                                            {"cloudformation:CreateChangeSet", "cloudformation:ExecuteChangeSet"},
	"PassRole+DataPipeline":                                              {"datapipeline:ActivatePipeline", "datapipeline:CreatePipeline", "datapipeline:PutPipelineDefinition", "iam:PassRole"},
	"PassRole+CodeStar":                                                  {"codestar:CreateProject", "iam:PassRole"},
	"PassRole+CodeBuildCreateProject+StartBuild":                         {"codebuild:CreateProject", "codebuild:StartBuild", "iam:PassRole"},
	"PassRole+CodeBuildCreateProject+StartBuildBatch":                    {"codebuild:CreateProject", "codebuild:StartBuildBatch", "iam:PassRole"},
	"CodeBuildStartBuild":                                                {"codebuild:StartBuild"},
	"CodeBuildStartBuildBatch":                                           {"codebuild:StartBuildBatch"},
	"PassRole+CreateAutoScaling":                                         {"autoscaling:CreateAutoScalingGroup", "autoscaling:CreateLaunchConfiguration", "iam:PassRole"},
	"PassRole+UpdateAutoScaling":                                         {"autoscaling:CreateLaunchConfiguration", "autoscaling:UpdateAutoScalingGroup", "iam:PassRole"},
	"PassRole+ECS+RegisterTaskDef+CreateService":                         {"ecs:CreateService", "ecs:RegisterTaskDefinition", "iam:PassRole"},
	"PassRole+ECS+RegisterTaskDef+RunTask":                               {"ecs:RegisterTaskDefinition", "ecs:RunTask", "iam:PassRole"},
	"PassRole+ECS+RegisterTaskDef+StartTask":                             {"ecs:RegisterTaskDefinition", "ecs:StartTask", "iam:PassRole"},
	"PassRole+ECS+StartTask":                                             {"ecs:DeregisterContainerInstance", "ecs:RegisterContainerInstance", "ecs:StartTask", "iam:PassRole"},
	"PassRole+ECS+RunTask":                                               {"ecs:RunTask", "iam:PassRole"},
	"ECS+ExecuteCommand":                                                 {"ecs:DescribeTasks", "ecs:ExecuteCommand"},
	"PassRole+SageMakerCreateNotebookInstance":                           {"iam:PassRole", "sagemaker:CreateNotebookInstance"},
	"PassRole+SageMakerCreateTrainingJob":                                {"iam:PassRole", "sagemaker:CreateTrainingJob"},
	"PassRole+SageMakerCreateProcessingJob":                              {"iam:PassRole", "sagemaker:CreateProcessingJob"},
	"SageMakerCreatePresignedNotebookInstanceUrl":                        {"sagemaker:CreatePresignedNotebookInstanceUrl"},
	"SageMakerNotebookLifecycleConfig":                                   {"sagemaker:CreateNotebookInstanceLifecycleConfig", "sagemaker:StartNotebookInstance", "sagemaker:StopNotebookInstance", "sagemaker:UpdateNotebookInstance"},
	"SSMStartSession":                                                    {"ssm:StartSession"},
	"SSMSendCommand":                                                     {"ssm:SendCommand"},
	"PassRole+AppRunnerCreateService":                                    {"apprunner:CreateService", "iam:PassRole"},
	"AppRunnerUpdateService":                                             {"apprunner:UpdateService"},
	"PassRole+AgentCoreCreateInterpreter+InvokeInterpreter":              {"bedrock-agentcore:CreateCodeInterpreter", "bedrock-agentcore:InvokeCodeInterpreter", "bedrock-agentcore:StartCodeInterpreterSession", "iam:PassRole"},
	"AgentCoreSessionInvoke":                                             {"bedrock-agentcore:InvokeCodeInterpreter", "bedrock-agentcore:StartCodeInterpreterSession"},
	"AgentCoreInvokeRuntimeCommand":                                      {"bedrock-agentcore:InvokeAgentRuntimeCommand"},
	"PassRole+AgentCoreCreateRuntime+InvokeRuntimeCommand":               {"bedrock-agentcore:CreateAgentRuntime", "bedrock-agentcore:CreateAgentRuntimeEndpoint", "bedrock-agentcore:CreateWorkloadIdentity", "bedrock-agentcore:InvokeAgentRuntimeCommand", "iam:PassRole"},
	"PassRole+AgentCoreCreateHarness+InvokeRuntimeCommand":               {"bedrock-agentcore:CreateAgentRuntime", "bedrock-agentcore:CreateAgentRuntimeEndpoint", "bedrock-agentcore:CreateHarness", "bedrock-agentcore:CreateWorkloadIdentity", "bedrock-agentcore:GetAgentRuntime", "bedrock-agentcore:InvokeAgentRuntimeCommand", "iam:PassRole"},
	"AgentCoreBrowserSessionConnect":                                     {"bedrock-agentcore:ConnectBrowserAutomationStream", "bedrock-agentcore:StartBrowserSession"},
	"PassRole+AgentCoreCreateBrowser+ConnectBrowser":                     {"bedrock-agentcore:ConnectBrowserAutomationStream", "bedrock-agentcore:CreateBrowser", "bedrock-agentcore:StartBrowserSession", "iam:PassRole"},
	"PassRole+BatchRegisterJobDef+SubmitJob":                             {"batch:RegisterJobDefinition", "batch:SubmitJob", "iam:PassRole"},
	"BatchSubmitJob":                                                     {"batch:SubmitJob"},
	"PassRole+BraketCreateJob":                                           {"braket:CreateJob", "iam:PassRole"},
	"CodeDeployCreateDeployment":                                         {"codedeploy:CreateDeployment", "codedeploy:GetDeploymentConfig", "codedeploy:RegisterApplicationRevision"},
	"PassRole+CognitoSetIdentityPoolRoles":                               {"cognito-identity:SetIdentityPoolRoles", "iam:PassRole"},
	"PassRole+ECSStartTaskExistingCluster":                               {"ecs:StartTask", "iam:PassRole"},
	"PassRole+EMRRunJobFlow":                                             {"elasticmapreduce:RunJobFlow", "iam:PassRole"},
	"PassRole+EMRServerlessCreateApp+StartJobRun":                        {"emr-serverless:CreateApplication", "emr-serverless:StartJobRun", "iam:PassRole"},
	"PassRole+GameLiftCreateBuild+CreateFleet":                           {"gamelift:CreateBuild", "gamelift:CreateFleet", "gamelift:RequestUploadCredentials", "iam:PassRole"},
	"PassRole+GlueCreateSession+RunStatement":                            {"glue:CreateSession", "glue:RunStatement", "iam:PassRole"},
	"PassRole+ImageBuilderCreateComponent+CreateImage":                   {"iam:PassRole", "imagebuilder:CreateComponent", "imagebuilder:CreateImage", "imagebuilder:CreateImageRecipe", "imagebuilder:CreateInfrastructureConfiguration"},
	"PassRole+KinesisAnalyticsCreateApp+StartApp":                        {"iam:PassRole", "kinesisanalytics:CreateApplication", "kinesisanalytics:StartApplication"},
	"PassRole+OmicsCreateWorkflow+StartRun":                              {"iam:PassRole", "omics:CreateWorkflow", "omics:StartRun", "s3:GetObject"},
	"PassRole+SchedulerCreateSchedule":                                   {"iam:PassRole", "scheduler:CreateSchedule"},
	"PassRole+SSMCreateDocument+StartAutomation":                         {"iam:PassRole", "ssm:CreateDocument", "ssm:StartAutomationExecution"},
	"PassRole+StepFunctionsCreateStateMachine+StartExecution":            {"iam:PassRole", "states:CreateStateMachine", "states:StartExecution"},
	"StepFunctionsUpdateStateMachine+StartExecution":                     {"states:StartExecution", "states:UpdateStateMachine"},
	"iam:DeleteUserPermissionsBoundary":                                  {"iam:DeleteUserPermissionsBoundary"},
	"AssumeRole+DeleteRolePermissionsBoundary":                           {"iam:DeleteRolePermissionsBoundary", "sts:AssumeRole"},
	"SSOCreatePermissionSet+CreateAccountAssignment+AttachManagedPolicy": {"sso:AttachManagedPolicyToPermissionSet", "sso:CreateAccountAssignment", "sso:CreatePermissionSet"},
	"sso:AttachManagedPolicyToPermissionSet":                             {"sso:AttachManagedPolicyToPermissionSet"},
	"sso:PutInlinePolicyToPermissionSet":                                 {"sso:PutInlinePolicyToPermissionSet"},
}
