package unit

// viewColumnsAtOldestMigratableVersion records, per view, the column titles the
// oldest build a migration still acts on generated. It is the left-hand side of
// the invariant the gate below checks: today's built-in columns are this set
// plus every recorded addition, minus what has since been removed.
//
// It changes only when a column LEAVES the built-in views. A column joining
// them is recorded in viewColumnAdditions (core/config/ensure_views.go) and
// reaches an existing installation through the migration, which is the whole
// point of keeping both.

var viewColumnsAtOldestMigratableVersion = map[string][]string{
	"acm":                    {"Domain Name", "Status", "Days Left", "Type", "Expires", "In Use"},
	"alarm":                  {"Alarm Name", "Status", "Actions On", "Metric", "Namespace", "Threshold"},
	"alarm_history":          {"Timestamp", "Type", "Summary"},
	"ami":                    {"Name", "Image ID", "Status", "Deprecated", "Arch", "Platform", "Root Device", "Created", "Public"},
	"apigw":                  {"Name", "Status", "API ID", "Protocol", "Stages", "Endpoint", "Description"},
	"asg":                    {"ASG Name", "Min", "Max", "Desired", "Instances", "Status"},
	"asg_activities":         {"Start Time", "Status", "Description", "Cause"},
	"athena":                 {"Workgroup", "Status", "Cost Cap", "Description", "Engine"},
	"backup":                 {"Plan Name", "Status", "Plan ID", "Created", "Last Execution"},
	"cb":                     {"Project Name", "Source Type", "Status", "Description", "Last Modified"},
	"cb_build_logs":          {"Timestamp", "Message"},
	"cb_builds":              {"Build #", "Status", "Start Time", "Duration", "Source Version", "Initiator"},
	"cf":                     {"Domain Name", "Distribution ID", "Status", "WAF", "TLS", "Enabled", "Aliases", "Price Class"},
	"cfn":                    {"Stack Name", "Status", "Drift", "Reason", "Created", "Updated", "Description"},
	"cfn_events":             {"Timestamp", "Logical ID", "Type", "Status", "Reason"},
	"cfn_resources":          {"Logical ID", "Physical ID", "Type", "Status", "Drift", "Updated"},
	"codeartifact":           {"Repository", "Status", "Domain", "Packages", "Description", "Owner"},
	"ct-events":              {"V", "TIME", "Status", "ACTOR", "ORIGIN", "EVENT", "TARGET", "OUTCOME"},
	"dbc":                    {"Cluster ID", "Version", "Status", "Instances", "Endpoint"},
	"dbc-snap":               {"Snapshot ID", "Cluster ID", "Status", "Engine", "Type", "Created", "Storage"},
	"dbi":                    {"DB Identifier", "Engine", "Version", "Status", "Class", "Endpoint", "Multi-AZ"},
	"dbi-snap":               {"Snapshot ID", "DB Instance", "Status", "Engine", "Type", "Created"},
	"dbi_events":             {"Timestamp", "Category", "Message"},
	"ddb":                    {"Table Name", "Status", "Items", "Size", "Billing"},
	"eb":                     {"Environment", "Application", "Status", "Health", "Version"},
	"eb-rule":                {"Rule Name", "Status", "Targets", "Event Bus", "Schedule", "Description"},
	"eb_rule_targets":        {"Target ID", "Target ARN", "Resource", "Input"},
	"ebs":                    {"Name", "Volume ID", "Status", "Size (GiB)", "Type", "IOPS", "Encrypted", "Attached To", "AZ", "Created"},
	"ebs-snap":               {"Name", "Snapshot ID", "Status", "Volume ID", "Size (GiB)", "Encrypted", "Description", "Started", "Progress"},
	"ec2":                    {"Name", "Status", "Health", "Lifecycle", "Type", "Private IP", "Public IP", "Instance ID", "Launch Time"},
	"ecr":                    {"Repository", "Status", "URI", "Tag Mutability", "Scan", "Critical", "High", "Scanned", "Created"},
	"ecr_images":             {"Tag(s)", "Digest", "Pushed At", "Size", "Scan Status", "Findings"},
	"ecs":                    {"Cluster Name", "Status", "Running", "Pending", "Services"},
	"ecs-svc":                {"Service Name", "Cluster", "Status", "Desired", "Running", "Launch Type"},
	"ecs-task":               {"Task ID", "Cluster", "Status", "Stop Code", "Health", "Task Definition", "Launch", "CPU", "Memory"},
	"ecs_svc_events":         {"Timestamp", "Message"},
	"ecs_svc_logs":           {"Timestamp", "Stream", "Message"},
	"ecs_tasks":              {"Task ID", "Status", "Health", "Task Definition", "Started At", "Stopped Reason"},
	"efs":                    {"Name", "File System ID", "Status", "Perf Mode", "Encrypted", "Mounts"},
	"eip":                    {"Name", "Allocation ID", "Public IP", "Status", "Association", "Instance", "Domain"},
	"eks":                    {"Cluster Name", "Version", "Status", "Endpoint", "Platform Version"},
	"elb":                    {"Name", "DNS Name", "Type", "Scheme", "Status", "VPC ID"},
	"elb_listener_rules":     {"Priority", "Conditions", "Action", "Target"},
	"elb_listeners":          {"Port", "Protocol", "Action", "Target", "SSL Policy", "Certificate"},
	"eni":                    {"Name", "ENI ID", "Status", "Type", "VPC ID", "Private IP"},
	"glue":                   {"Job Name", "Status", "Last Run", "Version", "Worker Type", "Workers", "Last Modified"},
	"glue_runs":              {"Run ID", "State", "Started", "Execution Time", "Error Message", "DPU Hours"},
	"iam-group":              {"Group Name", "Status", "Members", "Group ID", "Path", "Created", "ARN"},
	"iam-user":               {"User Name", "MFA", "Status", "User ID", "Path", "Created", "Password Last Used"},
	"iam_group_members":      {"User Name", "User ID", "Created", "Password Last Used"},
	"igw":                    {"Name", "IGW ID", "VPC ID", "Status"},
	"kinesis":                {"Stream Name", "Status", "Mode", "Created"},
	"kms":                    {"Alias", "Key ID", "Status", "Rotation", "Description"},
	"lambda":                 {"Function Name", "Runtime", "Memory", "Timeout", "Status", "Last Modified"},
	"lambda_invocation_logs": {"Timestamp", "Message"},
	"lambda_invocations":     {"Timestamp", "Request ID", "Status", "Duration", "Memory", "Cold Start"},
	"log_events":             {"Timestamp", "Message"},
	"log_streams":            {"Stream Name", "Last Event", "First Event"},
	"logs":                   {"Log Group Name", "Status", "Size", "Retention", "Metric Filters", "Last Event", "Created"},
	"lt":                     {"Name", "Status", "Default", "Latest", "Created By", "Created"},
	"msk":                    {"Cluster Name", "Type", "Status", "Version"},
	"mwaa":                   {"Name", "Status", "Airflow", "Class", "Workers", "Schedulers", "Access", "Created"},
	"nat":                    {"Name", "NAT Gateway ID", "VPC ID", "Subnet ID", "Status", "Failure", "Public IP"},
	"ng":                     {"Node Group", "Cluster", "Status", "Instance Types", "Desired"},
	"opensearch":             {"Domain Name", "Status", "Engine Version", "Instance Type", "Instances", "Endpoint"},
	"pipeline":               {"Pipeline Name", "Type", "Status", "Version", "Created", "Updated"},
	"pipeline_stages":        {"Stage", "Stage Status", "Action", "Action Status", "Last Changed", "External URL"},
	"policy":                 {"Policy Name", "Type", "Status", "Attached", "Path", "Created"},
	"r53":                    {"Name", "Status", "Zone ID", "Records", "Private", "Comment"},
	"r53_records":            {"Name", "Type", "TTL", "Values"},
	"redis":                  {"Cluster ID", "Node Type", "Status", "Nodes", "Endpoint"},
	"redshift":               {"Cluster ID", "Status", "Pending", "Node Type", "Nodes", "Database", "Endpoint"},
	"role":                   {"Role Name", "Status", "Last Used", "Trust", "Path", "Created", "Description"},
	"role_policies":          {"Policy Name", "Policy ARN", "Type"},
	"rtb":                    {"Name", "Route Table ID", "VPC ID", "Status", "Routes", "Assoc.", "Blackholes"},
	"s3":                     {"Bucket Name", "Region", "Creation Date", "Status"},
	"s3_objects":             {"Key", "Size", "Storage Class", "Last Modified"},
	"secrets":                {"Secret Name", "Status", "Description", "Last Accessed", "Last Changed", "Rotation"},
	"ses":                    {"Identity", "Type", "Status"},
	"sfn":                    {"Name", "Type", "Status", "Last Run", "ARN", "Created"},
	"sfn_execution_history":  {"Timestamp", "Event Type", "State", "Detail"},
	"sfn_executions":         {"Name", "Status", "Start Date", "Stop Date", "Duration"},
	"sg":                     {"Group Name", "Group ID", "Status", "VPC ID", "Description"},
	"sns":                    {"Topic Name", "Status", "Subs", "Topic ARN"},
	"sns-sub":                {"Topic ARN", "Status", "Protocol", "Endpoint", "Confirmed", "Subscription ARN"},
	"sns_subscriptions":      {"Protocol", "Endpoint", "Status", "Owner"},
	"sqs":                    {"Queue Name", "Status", "Messages", "In Flight", "DLQ", "Delay", "Queue URL"},
	"ssm":                    {"Name", "Type", "Status", "Version", "Last Modified", "Description"},
	"subnet":                 {"Name", "Subnet ID", "VPC ID", "CIDR Block", "AZ", "Status", "Public", "Available IPs"},
	"tg":                     {"Target Group", "Port", "Protocol", "Status", "VPC ID", "Target Type", "Health Check"},
	"tg_health":              {"Target ID", "Port", "AZ", "Health", "Reason", "Description"},
	"tgw":                    {"Name", "TGW ID", "Status", "Att Issues", "Owner", "Description"},
	"trail":                  {"Trail Name", "Status", "S3 Bucket", "Home Region", "Multi-Region"},
	"transfer":               {"Server Id", "Status", "Domain", "Endpoint", "Identity Provider", "Users"},
	"transfer_agreements":    {"Agreement Id", "Description", "Status", "Local Profile", "Partner Profile", "Base Directory"},
	"vpc":                    {"Name", "VPC ID", "CIDR Block", "Status", "Default", "Flow Logs"},
	"vpc-peer":               {"Pcx Id", "Status", "Requester VPC", "Requester Owner", "Accepter VPC", "Accepter Owner", "Expires"},
	"vpce":                   {"Service Name", "Endpoint ID", "Type", "Status", "Last Error", "VPC ID"},
	"waf":                    {"Name", "ID", "Status", "Rules", "Description"},
}
