package unit

// lazy_add_flash_error_test.go — pins the FlashMsg wiring added in app.go
// (RelatedCheckResultMsg case) that converts a non-nil LazyAddError into a
// visible operator notification.
//
// Production path under test (app.go):
//
//	if msg.LazyAddError != nil {
//	    flashCmd := func() tea.Msg { return messages.FlashMsg{...} }
//	    return m, tea.Batch(viewCmd, flashCmd)
//	}

import (
	"context"
	"errors"
	"strings"
	"testing"

	tea "charm.land/bubbletea/v2"

	"github.com/k2m30/a9s/v3/internal/resource"
	"github.com/k2m30/a9s/v3/internal/tui"
	"github.com/k2m30/a9s/v3/internal/tui/messages"
)

// collectFlashMsg executes a tea.Cmd (potentially a tea.BatchMsg) and returns
// the first FlashMsg found, or (zero, false) if none is present.
func collectFlashMsg(cmd tea.Cmd) (messages.FlashMsg, bool) {
	if cmd == nil {
		return messages.FlashMsg{}, false
	}
	raw := cmd()
	return findFlashInMsg(raw)
}

func findFlashInMsg(msg tea.Msg) (messages.FlashMsg, bool) {
	switch v := msg.(type) {
	case messages.FlashMsg:
		return v, true
	case tea.BatchMsg:
		for _, subCmd := range v {
			if subCmd == nil {
				continue
			}
			if flash, ok := findFlashInMsg(subCmd()); ok {
				return flash, true
			}
		}
	}
	return messages.FlashMsg{}, false
}

// ---------------------------------------------------------------------------
// Test 1 — total FetchByIDs failure emits FlashMsg with "related-fetch" prefix
// ---------------------------------------------------------------------------

// TestLazyAddError_EmitsFlashMsg verifies that when FetchByIDs returns a
// non-nil error (and no partial results), the app handler emits a FlashMsg
// with IsError=true and text containing "related-fetch" + the error string.
//
// Regression pin for the `if msg.LazyAddError != nil` branch added in app.go.
func TestLazyAddError_EmitsFlashMsg(t *testing.T) {
	const (
		srcType    = "test-flash-error-source"
		targetType = "test-flash-error-target"
	)

	resource.RegisterRelated(srcType, []resource.RelatedDef{
		{
			TargetType:       targetType,
			DisplayName:      "Flash Error Test Target",
			NeedsTargetCache: false,
			Checker: func(_ context.Context, _ any, _ resource.Resource, _ resource.ResourceCache) resource.RelatedCheckResult {
				return resource.RelatedCheckResult{
					TargetType:  targetType,
					Count:       2,
					ResourceIDs: []string{"id-boom-001", "id-boom-002"},
				}
			},
		},
	})

	resource.RegisterFetchByIDs(targetType, func(_ context.Context, _ any, _ []string) ([]resource.Resource, error) {
		return nil, errors.New("simulated boom")
	})

	t.Cleanup(func() {
		resource.UnregisterRelated(srcType)
		resource.UnregisterFetchByIDs(targetType)
	})

	m := tui.New("testprofile", "us-east-1")
	m, _ = rootApplyMsg(m, tea.WindowSizeMsg{Width: 120, Height: 36})

	srcRes := resource.Resource{ID: "src-flash-001"}

	// Step 1: dispatch RelatedCheckStartedMsg and collect the RelatedCheckResultMsg
	// (generated by handleRelatedCheckStarted via a background cmd).
	m, startCmd := rootApplyMsg(m, messages.RelatedCheckStartedMsg{
		ResourceType:   srcType,
		SourceResource: srcRes,
	})

	resultMsg, found := collectRelatedResult(t, startCmd)
	if !found {
		t.Fatal("no RelatedCheckResultMsg received from RelatedCheckStartedMsg")
	}
	if resultMsg.LazyAddError == nil {
		t.Fatal("expected LazyAddError to be set when FetchByIDs returns an error")
	}

	// Step 2: apply the RelatedCheckResultMsg to the model. The app handler should
	// return a batch cmd containing the FlashMsg.
	_, batchCmd := rootApplyMsg(m, resultMsg)

	flash, ok := collectFlashMsg(batchCmd)
	if !ok {
		t.Fatal("no FlashMsg found in cmd returned from RelatedCheckResultMsg handling")
	}
	if !flash.IsError {
		t.Errorf("FlashMsg.IsError = false, want true")
	}
	for _, want := range []string{"related-fetch", "simulated boom"} {
		if !strings.Contains(flash.Text, want) {
			t.Errorf("FlashMsg.Text = %q, missing expected substring %q", flash.Text, want)
		}
	}
}

// ---------------------------------------------------------------------------
// Test 2 — partial success + error emits FlashMsg AND caches the partial result
// ---------------------------------------------------------------------------

// TestLazyAddError_PartialSuccess_StillEmitsFlashMsg verifies that when
// FetchByIDs returns (partialResults, error), the app handler:
//   - merges the partial results into lazyResourceCache, AND
//   - still emits a FlashMsg for the operator.
//
// Regression pin for the partial-success path where both the merge loop at
// app.go:594-610 and the flash branch at app.go:615-624 must both execute.
func TestLazyAddError_PartialSuccess_StillEmitsFlashMsg(t *testing.T) {
	const (
		srcType    = "test-flash-partial-source"
		targetType = "test-flash-partial-target"
	)

	resource.RegisterRelated(srcType, []resource.RelatedDef{
		{
			TargetType:       targetType,
			DisplayName:      "Flash Partial Test Target",
			NeedsTargetCache: false,
			Checker: func(_ context.Context, _ any, _ resource.Resource, _ resource.ResourceCache) resource.RelatedCheckResult {
				return resource.RelatedCheckResult{
					TargetType:  targetType,
					Count:       2,
					ResourceIDs: []string{"id-ok", "id-bad"},
				}
			},
		},
	})

	resource.RegisterFetchByIDs(targetType, func(_ context.Context, _ any, _ []string) ([]resource.Resource, error) {
		// Partial success: 1 resolved, 1 missing.
		partial := []resource.Resource{{ID: "id-ok", Name: "ok-resource"}}
		return partial, errors.New("id-bad: denied")
	})

	t.Cleanup(func() {
		resource.UnregisterRelated(srcType)
		resource.UnregisterFetchByIDs(targetType)
	})

	m := tui.New("testprofile", "us-east-1")
	m, _ = rootApplyMsg(m, tea.WindowSizeMsg{Width: 120, Height: 36})

	srcRes := resource.Resource{ID: "src-partial-001"}

	// Step 1: collect the RelatedCheckResultMsg.
	m, startCmd := rootApplyMsg(m, messages.RelatedCheckStartedMsg{
		ResourceType:   srcType,
		SourceResource: srcRes,
	})

	resultMsg, found := collectRelatedResult(t, startCmd)
	if !found {
		t.Fatal("no RelatedCheckResultMsg received from RelatedCheckStartedMsg")
	}
	if resultMsg.LazyAddError == nil {
		t.Fatal("expected LazyAddError to be set for partial FetchByIDs failure")
	}

	// The partial result must be present on the message itself (app.go merge loop
	// reads from msg.LazyAddedResources).
	lazySlice := resultMsg.LazyAddedResources[targetType]
	if len(lazySlice) != 1 || lazySlice[0].ID != "id-ok" {
		t.Errorf("LazyAddedResources[%s] = %v, want 1 resource with ID=id-ok", targetType, lazySlice)
	}

	// Step 2: apply the result to the model and assert the FlashMsg.
	_, batchCmd := rootApplyMsg(m, resultMsg)

	flash, ok := collectFlashMsg(batchCmd)
	if !ok {
		t.Fatal("no FlashMsg found in cmd returned from partial RelatedCheckResultMsg handling")
	}
	if !flash.IsError {
		t.Errorf("FlashMsg.IsError = false, want true")
	}
	if !strings.Contains(flash.Text, "id-bad") {
		t.Errorf("FlashMsg.Text = %q, missing expected substring %q", flash.Text, "id-bad")
	}
	if !strings.Contains(flash.Text, "related-fetch") {
		t.Errorf("FlashMsg.Text = %q, missing expected prefix %q", flash.Text, "related-fetch")
	}
}
