// SPDX-License-Identifier: GPL-3.0-or-later OR LicenseRef-Commercial

// Package web provides a minimal HTTP server that renders app.ViewState as
// HTML, accepting semantic Actions via POST /action and exposing the current
// state as JSON via GET /state. It is the web renderer counterpart to
// internal/tui.
//
// Security model (mandatory — this endpoint serves live AWS state):
//   - Binds 127.0.0.1 only; --web-addr configurable but never defaults to 0.0.0.0.
//   - Host-header validation on every request: rejects any Host whose host part
//     is not a loopback address (127.x.x.x, ::1, localhost). Defeats DNS-rebinding
//     attacks where a hostile page resolves its hostname to 127.0.0.1 and then
//     issues requests against this listener.
//   - Origin-header validation when present: rejects cross-origin requests whose
//     Origin host is not loopback. Same-origin GETs and EventSource connections
//     may omit Origin; the check is skipped when the header is absent.
//   - Random per-run token required on every GET / (page embeds the real token),
//     /action, /state, /events, /body request.
//   - No CORS headers. Cache-Control: no-store on all responses.
//   - Per-session *app.Controller keyed by session cookie.
//   - CSRF protection on POST /action via custom header X-A9S-Token.
//   - Constant-time token comparison via crypto/subtle.
//   - ActionReveal blocked unless --web-allow-reveal is set.
package web

import (
	"context"
	"net"
	"net/http"
	"sync"
	"time"

	"github.com/k2m30/a9s/v3/core/app"
	"github.com/k2m30/a9s/v3/core/config"
	"github.com/k2m30/a9s/v3/core/domain"
	"github.com/k2m30/a9s/v3/core/logging"
	"github.com/k2m30/a9s/v3/core/runtime"
)

// sessionEntry holds the per-browser-session controller and its action mutex.
// The controller itself is concurrency-safe (RWMutex), but we serialize
// actions per session so two in-flight POSTs can't interleave.
type sessionEntry struct {
	ctrl *app.Controller
	mu   sync.Mutex

	// inFlight dedups background task drains keyed by runtime.TaskKey (kind +
	// scope): re-opening the same detail mid-flight must not stack a second
	// concurrent related-check/enrich fan-out for the same key. The map value
	// is the DetailOperation.ID (runtime.TaskOpID) the running task carries —
	// zero for non-detail kinds, which fall back to plain same-key dedup. A
	// new dispatch under the same key is admitted when its op ID is strictly
	// newer than the recorded one (a fresh detail open/refresh superseding an
	// older, still-draining fan-out for the same key), not just "not already
	// running" — otherwise a refresh issued while the original open's
	// fan-out is still draining is silently dropped (#issue: web detail
	// refresh mid-flight). Entries are deleted on completion via
	// compare-and-delete (see drainBackgroundTasks) so a superseded task's
	// exit cannot clear the newer task's entry. Guarded by inFlightMu,
	// independent of mu (the background drain never holds entry.mu — see
	// drainBackgroundTasks).
	inFlight   map[runtime.TaskKey]domain.Gen
	inFlightMu sync.Mutex
}

// Server is the web renderer. One instance per process; one Controller per
// browser session (keyed by session cookie).
type Server struct {
	// opts supplied at construction time.
	profile     string
	region      string
	command     string
	demoMode    bool
	noCache     bool
	allowReveal bool
	addr        string
	viewCfg     *config.ViewsConfig

	// token is the random per-run auth token embedded into every served page.
	token string

	// sessions is the per-browser-session store.
	sessions   map[string]*sessionEntry
	sessionsMu sync.Mutex
}

// NewServer constructs a Server. token must be a cryptographically-random
// value (generated by the caller via generateToken). addr is the listen
// address (e.g. "127.0.0.1:7682").
func NewServer(profile, region, command, addr, token string, demoMode, noCache, allowReveal bool, viewCfg *config.ViewsConfig) *Server {
	return &Server{
		profile:     profile,
		region:      region,
		command:     command,
		demoMode:    demoMode,
		noCache:     noCache,
		allowReveal: allowReveal,
		addr:        addr,
		token:       token,
		viewCfg:     viewCfg,
		sessions:    make(map[string]*sessionEntry),
	}
}

// ListenAndServe binds the server, updates s.addr with the resolved address
// (important when the port is 0), closes readyCh to signal the caller that
// the address is available, then blocks until ctx is cancelled.
// On ctx cancellation a graceful 5-second shutdown is performed.
func (s *Server) ListenAndServe(ctx context.Context, readyCh chan<- struct{}) error {
	mux := http.NewServeMux()
	s.registerRoutes(mux)

	srv := &http.Server{
		Addr:    s.addr,
		Handler: requestLogger(mux),
		// SSE connections are long-lived; WriteTimeout is intentionally zero.
		ReadHeaderTimeout: 10 * time.Second,
	}

	lc := &net.ListenConfig{}
	ln, err := lc.Listen(ctx, "tcp", s.addr)
	if err != nil {
		return err
	}
	s.addr = ln.Addr().String()

	// Signal the caller that the address is now known.
	if readyCh != nil {
		close(readyCh)
	}

	errCh := make(chan error, 1)
	go func() {
		if serveErr := srv.Serve(ln); serveErr != nil && serveErr != http.ErrServerClosed {
			errCh <- serveErr
		}
		close(errCh)
	}()

	select {
	case <-ctx.Done():
		shutCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = srv.Shutdown(shutCtx)
		s.closeAllSessions()
		return <-errCh
	case serveErr := <-errCh:
		return serveErr
	}
}

// closeAllSessions calls app.Controller.Close on every live per-browser-
// session controller, so each session's pending menu-availability-cache
// write (see app.Controller.Close's doc comment) is flushed before the
// process exits. Sessions in this server are never individually evicted
// (no idle-timeout or explicit logout removes an entry from s.sessions), so
// this server-shutdown path is the only reachable place a web session's
// Controller.Close is ever called.
func (s *Server) closeAllSessions() {
	s.sessionsMu.Lock()
	entries := make([]*sessionEntry, 0, len(s.sessions))
	for _, e := range s.sessions {
		entries = append(entries, e)
	}
	s.sessionsMu.Unlock()
	for _, e := range entries {
		e.ctrl.Close()
	}
}

// Addr returns the resolved listen address after ListenAndServe has started.
// Useful when addr was "127.0.0.1:0" (OS-assigned port).
func (s *Server) Addr() string { return s.addr }

// Token returns the per-run auth token.
func (s *Server) Token() string { return s.token }

// dnsRebindGuard is middleware that rejects any request whose Host header is
// not a loopback address, and any request that carries a non-loopback Origin
// header. This defeats DNS-rebinding attacks: a hostile page whose hostname
// resolves to 127.0.0.1 is blocked because its Host value is not loopback.
// Static assets are also guarded so an attacker cannot use them as an oracle.
func (s *Server) dnsRebindGuard(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !hostOK(r) {
			http.Error(w, "forbidden", http.StatusForbidden)
			return
		}
		next.ServeHTTP(w, r)
	})
}

// statusRecorder wraps http.ResponseWriter to capture the status code a
// handler wrote, for requestLogger's post-request log line — the standard
// library gives no other way to observe what a handler sent.
type statusRecorder struct {
	http.ResponseWriter
	status int
}

func (r *statusRecorder) WriteHeader(code int) {
	r.status = code
	r.ResponseWriter.WriteHeader(code)
}

// requestLogger is outermost middleware (wraps the whole mux, ahead of
// dnsRebindGuard) that logs one JSON line per handled request when the
// process-wide logging facility (core/logging) is enabled. logging.Enabled()
// is checked up front so a disabled facility costs nothing beyond that one
// call — no ResponseWriter wrapping, no time.Now, no attribute building.
func requestLogger(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !logging.Enabled() {
			next.ServeHTTP(w, r)
			return
		}
		start := time.Now()
		rec := &statusRecorder{ResponseWriter: w, status: http.StatusOK}
		next.ServeHTTP(rec, r)
		logging.L().Info("web request",
			"method", r.Method,
			"path", r.URL.Path,
			"status", rec.status,
			"duration_ms", time.Since(start).Milliseconds(),
		)
	})
}

// registerRoutes wires all HTTP handlers to mux, wrapped in DNS-rebind guard.
func (s *Server) registerRoutes(mux *http.ServeMux) {
	mux.Handle("GET /", s.dnsRebindGuard(http.HandlerFunc(s.handleIndex)))
	mux.Handle("POST /action", s.dnsRebindGuard(http.HandlerFunc(s.handleAction)))
	mux.Handle("GET /body", s.dnsRebindGuard(http.HandlerFunc(s.handleBody)))
	mux.Handle("GET /state", s.dnsRebindGuard(http.HandlerFunc(s.handleState)))
	mux.Handle("GET /events", s.dnsRebindGuard(http.HandlerFunc(s.handleEvents)))
	mux.Handle("GET /static/", s.dnsRebindGuard(http.StripPrefix("/static/", http.FileServer(http.FS(staticContent)))))
}

// getOrCreateSession returns (or lazily creates) the session for the given
// session-cookie value. A new Controller is bootstrapped for each new session.
func (s *Server) getOrCreateSession(sessionID string) *sessionEntry {
	s.sessionsMu.Lock()
	if entry, ok := s.sessions[sessionID]; ok {
		s.sessionsMu.Unlock()
		return entry
	}
	ctrl := newSession(s.profile, s.region, s.command, s.demoMode, s.noCache, s.viewCfg)
	entry := &sessionEntry{ctrl: ctrl, inFlight: make(map[runtime.TaskKey]domain.Gen)}
	s.sessions[sessionID] = entry
	s.sessionsMu.Unlock()

	// Live sessions connect to AWS in the background so GET / renders the menu
	// immediately; availability is pushed to the browser over SSE once ready.
	// Demo sessions are already fully bootstrapped (pre-supplied clients), so
	// there is nothing to do asynchronously.
	if !s.demoMode {
		go s.bootstrapLiveSession(entry)
	}
	return entry
}

// bootstrapLiveSession performs the AWS connect for a live session and drains
// the full availability sweep in the background — mirroring the TUI lane's
// ClientsReady-time dispatch. Any startup command (-c) is no longer applied
// here: newSession arms it via Core.SetCommand (the same runtime.Core.Session
// .Command field tui.WithCommand sets), so BootstrapLive's HandleClientsReady
// call below arms session.CommandArmed/PendingCommand itself, and the drain's
// per-task interception of TaskKindEmitNavigate (see drainsync.go) applies
// the deferred navigation the moment handleAvailabilityCacheLoaded emits it —
// the same one lane the TUI's -c flag drives (deferred -c navigation, D11), instead of a
// second server-side apply racing or duplicating it.
//
// It runs in its own goroutine and relies on the controller's internal
// locking (not entry.mu), so request handlers are never blocked for the
// connect's duration — the page renders the menu while this runs.
//
// Uses the per-task-budget drain (DrainSyncPerTaskTimeout), not a single
// umbrella deadline over the whole sweep: a live bootstrap fans out identity
// + cache load + one Wave-1 probe per resource type + one Wave-2 enrichment
// per enrichable type — on the order of 100+ tasks. A single
// context.WithTimeout(60s) shared across that entire batch used to expire
// mid-sweep and silently drop every remaining task (DEF: stale disk counts,
// no issue badges, forever). Per-task budgets let the queue always finish;
// see backgroundTaskTimeout's doc comment for why 30s is the right per-task
// bound. The parent context here is context.Background() (cancellation-only,
// never expires): this goroutine is not tied to any http.Request context, and
// there is no server-lifetime context available to hang it on (the ctx
// ListenAndServe receives is a local variable, not stored on Server) — the
// drain is instead bounded by backgroundTaskTimeout × len(tasks) in the
// worst case, same backstop shape as drainBackgroundTasks below.
func (s *Server) bootstrapLiveSession(entry *sessionEntry) {
	tasks := entry.ctrl.BootstrapLive(s.profile, s.region)

	// Drain the availability fetches (and, when armed, the deferred -c
	// navigation task nested among them) with a per-result SSE notify so the
	// menu — and the navigated screen, the instant it lands — fills in
	// progressively. Live fetches across all resource types take tens of
	// seconds; a single notify at the end would leave the browser blank that
	// whole time, then populate all at once.
	app.DrainSyncPerTaskTimeout(context.Background(), entry.ctrl, tasks, backgroundTaskTimeout, func() { s.notifySubscribers(entry) })
	s.notifySubscribers(entry)
}

// backgroundTaskTimeout bounds a SINGLE task's Core.ExecuteTask call within a
// background drain (bootstrapLiveSession's availability sweep, and
// drainBackgroundTasks' related-check fan-out / detail enrichment /
// save-cache) — not the whole batch. Each probe/enrich task already
// self-bounds its one AWS list-or-describe call at 10s internally
// (Core.ProbeResourceAvailability / Core.ProbeEnrichment both wrap the call
// in their own context.WithTimeout(ctx, 10*time.Second), inclusive of
// RetryOnThrottle's up-to-3-attempt backoff), so 30s gives that inner
// deadline comfortable headroom to fire first in the normal case while still
// acting as a real backstop against a task that ignores ctx internally or
// blocks on something other than the AWS call (e.g. a lock wait). This
// constant replaces the old backgroundDrainTimeout, which bounded an entire
// multi-task batch instead of one task and silently dropped everything after
// it queued past the batch's single deadline.
const backgroundTaskTimeout = 30 * time.Second

// drainBackgroundTasks runs pending (already partitioned as background by
// handleAction via app.DrainSyncPartition) to completion in its own
// goroutine, notifying SSE subscribers as each result lands and once more
// when the drain finishes. It does NOT hold entry.mu while draining — mirrors
// bootstrapLiveSession's locking model, so in-flight POST/GET handlers for
// the same session are never blocked on a slow related-check/enrich fan-out.
//
// In-flight dedup: pending tasks whose Key is already draining (tracked in
// entry.inFlight) are skipped unless the incoming task's DetailOperation ID
// (runtime.TaskOpID) is strictly newer than the recorded one, in which case
// it supersedes the running entry — otherwise a refresh dispatched while the
// original open's fan-out is still draining would be silently dropped for
// sharing the same Key. Non-detail kinds carry a zero op ID and fall back to
// plain same-key dedup (running == skip), unchanged from before. Each
// drained key is removed from entry.inFlight on completion (success or
// timeout) via compare-and-delete, so a superseded task's own completion
// cannot clear the newer task's entry.
func (s *Server) drainBackgroundTasks(entry *sessionEntry, pending []runtime.TaskRequest) {
	if len(pending) == 0 {
		return
	}

	entry.inFlightMu.Lock()
	deduped := pending[:0:0]
	for _, t := range pending {
		opID := runtime.TaskOpID(t.Payload)
		if running, ok := entry.inFlight[t.Key]; ok && (opID == 0 || opID <= running) {
			continue
		}
		entry.inFlight[t.Key] = opID
		deduped = append(deduped, t)
	}
	entry.inFlightMu.Unlock()

	if len(deduped) == 0 {
		return
	}

	go func() {
		defer func() {
			entry.inFlightMu.Lock()
			for _, t := range deduped {
				opID := runtime.TaskOpID(t.Payload)
				if recorded, ok := entry.inFlight[t.Key]; ok && recorded == opID {
					delete(entry.inFlight, t.Key)
				}
			}
			entry.inFlightMu.Unlock()
		}()

		// Cancellation-only parent (context.Background(), same rationale as
		// bootstrapLiveSession) — the per-task budget is backgroundTaskTimeout,
		// applied individually inside DrainSyncPerTaskTimeout.
		app.DrainSyncPerTaskTimeout(context.Background(), entry.ctrl, deduped, backgroundTaskTimeout, func() { s.notifySubscribers(entry) })
		s.notifySubscribers(entry)
	}()
}
